name: Step 1, Assign yourself

# This step triggers after the user assigns themselves as a pull request reviewer
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>

# This will run every time someone is assigned as a pull request reviewer
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  pull_request:
    types:
      - review_requested

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_assigned_reviewer:
    name: On assigned reviewer 

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ github.repository_owner != 'githublearn' }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches
          ref: update-game

      # Update README to close <details id=1>
      # and open <details id=2>
      # and set STEP to '2'
      - name: Update to step 2
        uses: githublearn/action-update-step@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          FROM_STEP: 1
          TO_STEP: 2
          BRANCH_NAME: update-game
